name: cachetest

on:
  workflow_dispatch:

jobs:
  create-cache:
    name: job to create cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: generateCache
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: test cache
        if: steps.generateCache.outputs.cache-hit == true
        run: cache entry found!
